#!/bin/bash

QUEUE=default
UDATA_PATH=/srv/udata/bin/udata
UDATA_SETTINGS=/srv/udata/udata.cfg

if [ "$1" = "config" ]; then
    UDATA_SETTINGS=$UDATA_SETTINGS $UDATA_PATH worker status --munin-config -q $QUEUE
else
    UDATA_SETTINGS=$UDATA_SETTINGS $UDATA_PATH worker status --munin -q $QUEUE
fi
