#!/bin/bash

# to be executed as `udata` user (with pyenv activated)

QUEUE=default

if [ "$1" = "config" ]; then
    udata worker status --munin-config -q $QUEUE
else
    udata worker status --munin -q $QUEUE
fi
