#!/usr/bin/env python
from __future__ import print_function

import sys
import os
import pymongo

# Fetch config
URI = os.environ.get('MONGO_URI', 'localhost')
NAME = 'connections'


def get_status(key):
    client = pymongo.MongoClient(URI)
    status = client.admin.command('serverStatus', workingSet=True)
    return status[key]


def get_data():
    print('{0}.value {1}'.format(NAME, get_status('connections')['current']))


def get_config():
    print('graph_title MongoDB current connections')
    print('graph_args --base 1000 -l 0')
    print('graph_vlabel connections')
    print('graph_category MongoDB')
    print('{0}.label {0}'.format(NAME))


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'config':
        get_config()
    else:
        get_data()
