#!/usr/bin/env python
from __future__ import print_function

import sys
import os
import pymongo

# Config
URI = os.environ.get('MONGO_URI', 'localhost')


def get_status(key):
    client = pymongo.MongoClient(URI)
    status = client.admin.command('serverStatus', workingSet=True)
    return status[key]


def get_data():
    for k, v in get_status('opcounters').items():
        print('{0}.value {1}'.format(k, v))


def get_config():
    print('graph_title MongoDB ops')
    print('graph_args --base 1000 -l 0')
    print('graph_vlabel ops / ${graph_period}')
    print('graph_category MongoDB')
    print('graph_total total')

    for key in get_status('opcounters'):
        print('{0}.label {0}'.format(key))
        print('{}.min 0'.format(key))
        print('{}.type COUNTER'.format(key))
        print('{}.max 500000'.format(key))
        print('{}.draw LINE1'.format(key))


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'config':
        get_config()
    else:
        get_data()
